---
# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

_extends: .github:.github/settings.yml

# repo-specific settings

repository:
  name: "portefaix-website"
  description: "Website of Portefaix project"
  topics: portefaix, docsy, website,

labels:

## CLOUD PROVIDERS

- name: "cloud/gcp"
  description: "Cloud Provider / Google Cloud Provider"
  color: "068082"

- name: "cloud/aws"
  description: "Cloud Provider / Amazon AWS"
  color: "068082"

- name: "cloud/azure"
  description: "Cloud Provider / Microsoft Azure"
  color: "068082"

- name: "cloud/scaleway"
  description: "Cloud Provider / Scaleway"
  color: "068082"

- name: "cloud/digitalocean"
  description: "Cloud Provider / Digital Ocean"
  color: "068082"

- name: "cloud/alicloud"
  description: "Cloud Provider / Alicloud"
  color: "068082"

- name: "cloud/exoscale"
  description: "Cloud Provider / Exoscale"
  color: "068082"

- name: "cloud/homelab"
  description: "Cloud Provider / Homelab"
  color: "068082"

- name: "cloud/cicd"
  description: "Cloud Provider / CICD"
  color: "068082"

- name: "cloud/vultr"
  description: "Cloud Provider / Vultr"
  color: "068082"

- name: "cloud/civo"
  description: "Cloud Provider / Civo"
  color: "068082"

- name: "cloud/oci"
  description: "Cloud Provider / OCI"
  color: "068082"

- name: "cloud/ibmcloud"
  description: "Cloud Provider / IBMCloud"
  color: "068082"

## NEED

- name: "needs/cloud"
  description: "Indicates a PR lacks a `cloud/foo` label and requires one."
  color: "D669BE"


## AREA

- name: "area/kubernetes"
  description: "Kubernetes"
  color: "cc317c"

- name: "area/docsy"
  description: "Docsy"
  color: "cc317c"

## DEPENDENCY

- name: "dependency/docsy"
  description: "Dependency Docsy"
  color: "6fcb70"
